# Generated by Django 3.2.4 on 2021-07-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='datetime',
            new_name='datetime_found',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='title',
        ),
    ]
